name: Deploy Lambda and Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Package Lambda
        run: |
          cd lambda
          zip -r ../lambda.zip .
          echo "Lambda package created successfully."
          ls -la ../lambda.zip

      - name: Upload Lambda to S3
        run: |
          aws s3 cp ./lambda.zip s3://golf-outing-lambda-deployments/lambda.zip

      - name: Deploy Lambda Function
        run: |
          aws lambda create-function \
            --function-name GolfOutingHandler \
            --runtime nodejs18.x \
            --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/golf_outing_lambda_role \
            --handler index.handler \
            --code S3Bucket=golf-outing-lambda-deployments,S3Key=lambda.zip \
            --environment Variables="{DYNAMODB_TABLE=GolfOutingTable}" \
            || aws lambda update-function-code \
            --function-name GolfOutingHandler \
            --s3-bucket golf-outing-lambda-deployments \
            --s3-key lambda.zip

      - name: Validate Deployment
        run: |
          echo "Validating deployment..."
          curl -I https://$(terraform output -raw cloudfront_distribution_id) || echo "Validation failed"
