name: Deploy Lambda and Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      S3_GOLF_BUCKET: golf-outing-manager
      REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Python Dependencies
        run: |
          cd lambda
          pip install -r requirements.txt -t package

      - name: Package Lambda Function
        run: |
          cd lambda
          ./package_lambda.sh
          ls -l lambda.zip  # Debugging: Ensure ZIP exists

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Show Terraform Outputs
        run: |
          echo "Terraform Outputs:"
          terraform -chdir=terraform output

      - name: Sync Web files to S3 ${{ env.S3_GOLF_BUCKET }}
        run: |
          aws s3 sync ./src s3://${{ env.S3_GOLF_BUCKET }} --delete
          echo "Static web files synced to S3 bucket."


      - name: Validate CloudFront Deployment
        run: |
          cd terraform
          CLOUDFRONT_URL=$(terraform output -raw s3_bucket_website_url || echo "Failed to fetch Cloudfront Domain")
          echo "Cloudfront Domain: $CLOUDFRONT_URL"
          echo "Attempting to validate..."
          if [[ -z "$CLOUDFRONT_URL" ]]; then
            echo "Cloudfront Domain is empty. Skipping validation."
            exit 0
          fi
          curl -I https://$CLOUDFRONT_URL || echo "Validation failed but continuing deployment"

      - name: Validate API Gateway Deployment
        run: |
          echo "Validating deployment..."
          terraform -chdir=terraform output api_gateway_url
