name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'  # Run only if files in /lambda change
      - 'terraform/**' # Run if Terraform files change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Force Redeploy if Lambda Code Changes
        run: terraform apply -auto-approve
