name: Populate Courses to AWS DynamoDB
on:
  push:
    branches:
      - main
    paths:
      - data/courses.json  # This line ensures the action runs only if the courses.json file changes
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy infrastructure
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
      - name: Sync S3
        run: |
          aws s3 sync src/ s3://your-bucket-name --delete
