name: Populate Courses to AWS DynamoDB

on:
  push:
    branches:
      - main
    paths:
      - data/courses.json
jobs:
  populate-database:
    runs-on: ubuntu-latest

    env:
      REGION: us-east-1
      DYNAMODB_TABLE: GolfOutingCoursesTable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run database population script
        run: |
          node ./scripts/populate-courses.js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
